on: pull_request_target

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const comment = `
              A documentation preview will be available soon:</br>
              <ul><li>📚 [HTML diff](https://${context.repo.repo}_${pr.number}.docs-preview.app.elstc.co/diff)</li>
              <li>📘 [Enterprise Search Guide](https://${context.repo.repo}_${pr.number}.docs-preview.app.elstc.co/guide/en/enterprise-search/master/index.html)</li>
              <li>📗 [App Search Guide](https://${context.repo.repo}_${pr.number}.docs-preview.app.elstc.co/guide/en/app-search/master/index.html)</li>
              <li>📙 [Workplace Search Guide](https://${context.repo.repo}_${pr.number}.docs-preview.app.elstc.co/guide/en/workplace-search/master/index.html)</li></ui>`;
            
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment,
            });
