name: Table Automation
on:
  issues:
    types: [labeled,unlabeled]

jobs:
  sync_issues_with_table:
    runs-on: ubuntu-latest
    name: Sync issues with table
    steps:
      - name: Sync issues with table
        uses: richkuz/table-github-actions@main
        id: sync_with_table
        with:
          ghToken: ${{ secrets.GITHUB_TOKEN }}
          sync-with-table: |
            [
              {"label": "label1", "tableNumber": "1"}
            ]
